### ISSUE TITLE
Book List Page

### ISSUE THREAD

**Issue by rahulbarwal** [OSC-2020/skill-up-backend#1]
## Phase 1:
Ability to:
- [x] Create a book group.
- [x] Delete a book group.
- [ ] Edit and update all 4 books in a group;
- [x] Each will have a title.

## Phase 2
- [x] Each collection will have a publish/unpublish button depending upon a flag `published= true/false`

**Comment by rahulbarwal** [comment]
Remaining point will be tracked via #9
